# Dataset / Model parameters
data_dir: /dataset/CIFAR100
dataset: torch/cifar100
pretrained: False
num_classes: 100
num_heads: 12
img_size: 32
mean:
    - 0.5071
    - 0.4867
    - 0.4408
std:
    - 0.2675
    - 0.2565
    - 0.2761
crop_pct: 1.0
scale:
    - 1.0
    - 1.0
ratio: [1.0, 1.0]
interpolation: bicubic
train_interpolation: bicubic
# use_conv_as_linear: true
pooling_stat: "0011"
time_steps: 4
layer: 4
dim: 384
mlp_ratio: 4.0
num_experts: 4
expert_timesteps: [4, 1, 1, 1] #"--expert-timesteps",

# Augmentation & regularization parameters
aa: rand-m9-n1-mstd0.4-inc1
color_jitter: 0.5
mixup: 0.5
mixup_off_epoch: 10
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 0.0

# Model Exponential Moving Average
model-ema: False
model-ema-decay: 0.9998

# Misc
seed: 42
amp: False  # True triggers CuDNN "no valid convolution algorithms" on backward with this model
channels_last: False
batch_size: 128
val_batch_size: 128
lr: 5e-4
min_lr: 1e-5
sched: cosine
weight_decay: 2e-2
epochs: 30
cooldown_epochs: 10
warmup_epochs: 3
warmup_lr: 5e-6
opt: adamw
smoothing: 0.1
workers: 8

# KD
router_kd: true
router_kd_weight: 0.2
router_kd_temp: 3.0
router_kd_warmup: linear   # [none, linear]
router_kd_warmup_epochs: 3
